# Generated by Django 5.0.8 on 2024-08-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="availabe",
            new_name="available",
        ),
    ]
